# 🌌 Human-AI Resonance Report Generator
# 간소화된 보고서 생성 (syntax error 회피)

from pathlib import Path
from datetime import datetime
from typing import Dict, Any, Optional


def generate_resonance_report(
    report_path: Path,
    session: Any,
    summary: Dict[str, Any],
    recommendation_rationale: Optional[Dict[str, Any]] = None,
):
    """상세 분석 보고서 작성 - 안전 버전"""

    with report_path.open("w", encoding="utf-8") as f:
        # 간단한 헤더만
        f.write("# Human-AI Resonance Analysis Report\n\n")
        f.write(f"Session ID: {getattr(session, 'id', 'unknown')}\n")
        f.write(f"Generated: {datetime.now().strftime('%Y-%m-%d %H:%M:%S')}\n\n")

        # 요약 점수 (안전하게)
        f.write("## Overall Summary\n\n")
        if summary:
            f.write(f"Overall Score: {summary.get('overall_score', 'N/A')}\n")
            f.write(f"Quality Level: {summary.get('quality_label', 'N/A')}\n\n")

        # 추천사항 (간단히)
        if recommendation_rationale:
            f.write("## Recommendations\n\n")
            for key, value in recommendation_rationale.items():
                f.write(f"- {key}: {value}\n")

        f.write("\n---\nReport generated by Echo Resonance Kit\n")


# 편의 함수 (원본 API 호환)
def write_resonance_report(*args, **kwargs):
    """원본 API 호환성 유지"""
    return generate_resonance_report(*args, **kwargs)
