name: AgentHub Tests
on:
  workflow_dispatch:
  push:
    paths:
      - "tests/agent_hub/**"
      - ".github/workflows/agent_hub_ci.yml"
      - "agent_hub/**"

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: "3.12"
      - name: Install deps
        run: |
          pip install requests pyyaml aiohttp
          pip install -r agent_hub/requirements.txt
      - name: (Optional) Start local server
        run: echo "CI에서는 별도 서버 필요. self-hosted 러너로 운영하거나 사전 기동 환경 사용."
      - name: Smoke (skipped if server absent)
        run: |
          set -e
          python - <<'PY'
import os, sys, requests
try:
    r = requests.get("http://localhost:8014/health", timeout=2)
    print("Server present:", r.status_code)
    sys.exit(0)
except Exception:
    print("No local server in CI; skipping.")
    sys.exit(0)
PY
      - name: Regression (skippable)
        if: always()
        run: |
          echo "If server is reachable, you can run:"
          echo "python tests/agent_hub/run_regression.py tests/agent_hub/regression.yaml || true"